version: '3.9'

volumes:
  mongodb: {}

services:
  nest-app:
    container_name: get-your-feeds-NestJS
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - mynetwork
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_URI: ${DATABASE_URI}
      NODE_ENV: ${NODE_ENV}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: get-your-feeds-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - mynetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  
  mongo-express:
    image: mongo-express
    container_name: get-your-feeds-mxpress
    restart: always
    ports:
      - 8081:8081
    networks:
      - mynetwork
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

networks:
  mynetwork: