name: CI

on:
  push:
    branches: [feature/*]

jobs:
  setup-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

  run-tests:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Run Tests with Coverage
        run: npm run test:cov

  run-format-lint:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Run Format
        run: npm run format
      - name: Run Lint
        run: npm run lint
