name: CI

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [feature/*, main]

jobs:
  nest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker compose Build
        run: docker-compose build

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Tests with Coverage using Docker Compose
        run: docker-compose exec nest-app npm run test:cov

      - name: Run Format using Docker Compose
        run: docker-compose exec nest-app npm run format

      - name: Run Lint using Docker Compose
        run: docker-compose exec nest-app npm run lint

      - name: Shut down Docker Compose
        run: docker-compose down
