name: CI

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [feature/*, main]

jobs:
  nest-test:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: local
      ALLOWED_ORIGIN: http://localhost:5173,http://127.0.0.1:5173
      DATABASE_NAME: db
      DATABASE_USER: admin
      DATABASE_PASS: admin
      DATABASE_URI: mongodb://database:27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@database:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker compose Build
        run: docker-compose build

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Tests with Coverage using Docker Compose
        run: docker-compose run nest-app npm run test:cov

      - name: Run Format using Docker Compose
        run: docker-compose run nest-app npm run format

      - name: Run Lint using Docker Compose
        run: docker-compose run nest-app npm run lint

      - name: Shut down Docker Compose
        run: docker-compose down